name: code-review

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  kmp-ios:
    name: kmp-ios
    runs-on: macOS-latest
    # Only run build in template repo
    # if: github.event.repository.name == 'KMP-App-Template-Native' && github.repository_owner == 'Kotlin'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer
      - name: iOS debug build
        run: cd iosApp && xcodebuild -scheme iosApp -configuration Debug -destination 'platform=iOS Simulator,OS=latest,name=iPhone 15' CODE_SIGNING_ALLOWED='NO'
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kmp-ios.app
          path: /Users/runner/Library/Developer/Xcode/DerivedData/iosApp-guppqqfdhdiftkfglvxojxmqinzi/Build/Products/Debug-iphonesimulator/spacecraft-kmp.app


  kmp-android:
    name: kmp-android
    runs-on: macOS-latest
    # Only run build in template repo
    # if: github.event.repository.name == 'kmp' && github.repository_owner == 'Kotlin'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Kmp Android debug build
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kmp-android.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  kmp-desktop:
    name: kmp-desktop
    runs-on: macOS-latest
    # Only run build in template repo
    # if: github.event.repository.name == 'kmp' && github.repository_owner == 'Kotlin'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Kmp Android debug build
        run: ./gradlew assembleDebug --stacktrace
